version: '2'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'nss_prueba'
      POSTGRES_PASSWORD: 'yourpassword'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass yourpassword
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  web:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'box'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    volumes_from:
      - box
    env_file:
      - '.env'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'box'
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/app'
    volumes_from:
      - box
    env_file:
      - '.env'

  cable:
    depends_on:
      - 'redis'
      - 'box'
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - '.:/app'
    volumes_from:
      - box
    env_file:
      - '.env'

  tests:
    depends_on:
      - 'redis'
      - 'postgres'
      - 'box'
    build: .
    volumes:
      - '.:/app'
    volumes_from:
      - box
    env_file:
      - '.env'
    environment:
      RAILS_ENV: test
      ACTION_CABLE_MOUNT: '/cable'
    command: /bin/true


  box:
    image: busybox
    volumes:
      - '/box'

volumes:
  redis:
  postgres:
